name: Deploy Terraform to AWS

on:
  push:
    branches: [master]

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Terraform Init
        run: terraform init
        working-directory: ./uat  # change this if your Terraform is elsewhere

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./uat

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./uat

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./uat
