name: Terraform UAT Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'environments/uat/**'
      - '.github/workflows/uat.yml'
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform UAT Apply'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/uat

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -backend-config="key=uat/terraform.tfstate"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve -input=false -var-file="terraform.tfvars"
